#!/usr/bin/env bash
# ADR-068 §2.1 — build mp-wasm for the BROWSER (Vite) and vendor the artifacts
# into client-game so `npm ci` worktrees / CI never need the Rust toolchain.
#
#   target:  --target web  → an ES module with an explicit async `init()`,
#            the proven browser path (browser_demo.html). Vite consumes it
#            natively (no vite-plugin-wasm, no optimizeDeps, no fs.allow entry):
#            MpRealClient does `import init` + a `?url` asset import of the .wasm.
#
#   vendor:  copy pkg-web/{mp_wasm.js,mp_wasm_bg.wasm,*.d.ts} →
#            client-game/src/vendor/mp-wasm/  (committed; @generated banner).
#            pkg-web/ stays gitignored (staging only).
#
# Re-running this is a DELIBERATE, reviewed step — the crypto is high-stakes, so
# the regenerated diff gets the model-tier + codex gate before merge.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
vendor="$here/../client-game/src/vendor/mp-wasm"

echo "[build-web] wasm-pack build --target web --out-dir pkg-web --release"
( cd "$here" && wasm-pack build --target web --out-dir pkg-web --release )

mkdir -p "$vendor"
for f in mp_wasm.js mp_wasm_bg.wasm mp_wasm.d.ts mp_wasm_bg.wasm.d.ts; do
  src="$here/pkg-web/$f"
  if [ ! -f "$src" ]; then
    echo "[build-web] ERROR: expected artifact missing: $src" >&2
    exit 1
  fi
  cp "$src" "$vendor/$f"
done

# Prepend a @generated banner to the JS + d.ts (NOT the binary .wasm).
banner_js="// @generated by mp-wasm/build-web.sh — do not edit by hand (ADR-068 §2.1)."
for f in mp_wasm.js mp_wasm.d.ts mp_wasm_bg.wasm.d.ts; do
  tmp="$(mktemp)"
  printf '%s\n' "$banner_js" > "$tmp"
  cat "$vendor/$f" >> "$tmp"
  mv "$tmp" "$vendor/$f"
done

echo "[build-web] vendored → $vendor"
ls -la "$vendor"
